String diagnosticLine(
  String timestamp, {
  required String refreshId,
  required String source,
  required String module,
  required String operation,
  String level = 'info',
  String status = '-',
  String durationMs = '-',
  bool relogged = false,
  bool retried = false,
  bool cacheUsed = false,
  String url = '-',
  String exceptionType = '-',
  String exception = '-',
  String message = '-',
  String stack = '-',
  String relatedRefreshId = '-',
}) {
  return '$timestamp | level=$level | refreshId=$refreshId | '
      'relatedRefreshId=$relatedRefreshId | source=$source | module=$module | '
      'operation=$operation | url=$url | status=$status | '
      'contentType=- | location=- | durationMs=$durationMs | '
      'relogged=$relogged | retried=$retried | cacheUsed=$cacheUsed | '
      'exceptionType=$exceptionType | exception=$exception | '
      'message=$message | stack=$stack';
}

String buildComprehensiveDiagnosticExportFixture() {
  return [
    'Celechron 诊断日志',
    '=== 5. 完整原始日志（UTC） ===',
    buildLatestDiagnosticFixture(),
    diagnosticLine(
      '2026-07-16T11:58:10.000Z',
      refreshId: 'shared-caller',
      relatedRefreshId: 'fg-success',
      source: 'foreground',
      module: 'refresh',
      operation: 'shareFlight',
      message: '同账号同操作已共享正在执行的 Future',
    ),
    diagnosticLine(
      '2026-07-16T11:58:10.020Z',
      refreshId: 'queued-login',
      source: 'foreground',
      module: 'refresh',
      operation: 'queueOperation',
      message: '同账号不同操作已按顺序等待',
    ),
  ].join('\n');
}

String buildLatestDiagnosticFixture() {
  return [
    diagnosticLine(
      '2026-07-16T11:53:32.000Z',
      refreshId: 'bg-refresh',
      source: 'background',
      module: 'refresh',
      operation: 'start',
      message: '完整刷新开始',
    ),
    diagnosticLine(
      '2026-07-16T11:53:37.000Z',
      refreshId: 'bg-refresh',
      source: 'background',
      module: '作业',
      operation: 'result',
      message: '实时成功',
    ),
    diagnosticLine(
      '2026-07-16T11:58:03.800Z',
      refreshId: '-',
      source: 'foreground',
      module: 'refresh',
      operation: 'foregroundActive',
      message: 'App 已进入前台',
    ),
    diagnosticLine(
      '2026-07-16T11:58:04.000Z',
      refreshId: 'fg-degraded',
      source: 'foreground',
      module: 'refresh',
      operation: 'start',
      message: '完整刷新开始',
    ),
    diagnosticLine(
      '2026-07-16T11:58:04.200Z',
      refreshId: 'fg-degraded',
      source: 'foreground',
      module: '教务网课表接口',
      operation: 'httpResponse',
      status: '922',
      url: 'https://zdbk.zju.edu.cn/jwglxt/kbcx/xskbcx_cxXsKb.html',
      message: '响应摘要：<文本响应；长度=0>',
    ),
    diagnosticLine(
      '2026-07-16T11:58:04.230Z',
      refreshId: 'fg-degraded',
      source: 'foreground',
      module: '教务网课表缓存',
      operation: 'readCache',
      cacheUsed: true,
      message: '使用缓存；缓存时间=2026-07-16T11:45:00.000Z',
    ),
    diagnosticLine(
      '2026-07-16T11:58:04.300Z',
      refreshId: 'fg-degraded',
      source: 'foreground',
      module: '课表',
      operation: 'result',
      message: '课表：实时请求失败，已使用缓存',
    ),
    diagnosticLine(
      '2026-07-16T11:58:04.350Z',
      refreshId: 'fg-degraded',
      source: 'foreground',
      module: '教务网考试接口',
      operation: 'httpResponse',
      status: '901',
      url: 'https://zdbk.zju.edu.cn/jwglxt/xskscx/kscx_cxXsgrksIndex.html',
      message: '响应摘要：<文本响应；长度=0>',
    ),
    diagnosticLine(
      '2026-07-16T11:58:05.050Z',
      refreshId: 'fg-degraded',
      source: 'foreground',
      module: '教务网考试接口',
      operation: 'httpResponse',
      status: '200',
      relogged: true,
      retried: true,
      message: '响应摘要：<JSON对象；字段数=2>',
    ),
    diagnosticLine(
      '2026-07-16T11:58:05.100Z',
      refreshId: 'fg-degraded',
      source: 'foreground',
      module: '考试',
      operation: 'result',
      message: '实时成功',
    ),
    diagnosticLine(
      '2026-07-16T11:58:05.200Z',
      refreshId: 'fg-degraded',
      source: 'foreground',
      module: '成绩',
      operation: 'result',
      relogged: true,
      retried: true,
      message: '实时成功',
    ),
    diagnosticLine(
      '2026-07-16T11:58:05.300Z',
      refreshId: 'fg-degraded',
      source: 'foreground',
      module: '教务网主修成绩接口',
      operation: 'exception',
      exceptionType: '_TypeError',
      exception: 'Null check operator used on a null value',
      stack: r'#0 Zdbk.getMajorGrade (zdbk.dart:373)\n#1 refresh',
    ),
    diagnosticLine(
      '2026-07-16T11:58:05.350Z',
      refreshId: 'fg-degraded',
      source: 'foreground',
      module: '教务网主修成绩缓存',
      operation: 'readCache',
      cacheUsed: true,
      message: '使用缓存；缓存时间=2026-07-16T11:45:00.000Z',
    ),
    diagnosticLine(
      '2026-07-16T11:58:05.400Z',
      refreshId: 'fg-degraded',
      source: 'foreground',
      module: '主修',
      operation: 'result',
      message: '主修：实时请求失败，已使用缓存',
    ),
    diagnosticLine(
      '2026-07-16T11:58:06.128Z',
      refreshId: 'fg-degraded',
      source: 'foreground',
      module: 'refresh',
      operation: 'finish',
      durationMs: '2128',
      message: '完整刷新结束',
    ),
    diagnosticLine(
      '2026-07-16T11:58:08.000Z',
      refreshId: 'fg-success',
      source: 'foreground',
      module: 'refresh',
      operation: 'start',
      message: '完整刷新开始',
    ),
    diagnosticLine(
      '2026-07-16T11:58:08.050Z',
      refreshId: 'fg-success',
      source: 'foreground',
      module: '校历',
      operation: 'futureProbe',
      status: '404',
      message: '未来学年校历未发布，已使用默认配置回退',
    ),
    for (var index = 0; index < 7; index++)
      diagnosticLine(
        '2026-07-16T11:58:0${8 + (index ~/ 5)}.${100 + index}Z',
        refreshId: 'fg-success',
        source: 'foreground',
        module: const ['校历', '课表', '考试', '成绩', '主修', '作业', '实践'][index],
        operation: 'result',
        message: '实时成功',
      ),
    diagnosticLine(
      '2026-07-16T11:58:09.741Z',
      refreshId: 'fg-success',
      source: 'foreground',
      module: 'refresh',
      operation: 'finish',
      durationMs: '1741',
      message: '完整刷新结束',
    ),
  ].join('\n');
}
