name: celechron
description: Cele, a calendar and task manager for ZJU only.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  animations: ^2.0.7

  table_calendar: any
  hive: ^2.2.3
  hive_flutter: any
  icalendar_parser: ^1.1.1
  const_date_time: ^1.0.2
  intl: ^0.18.0
  uuid: ^3.0.7
  settings_ui: ^2.0.2
  timezone: ^0.9.1
  flutter_native_timezone: ^2.0.0
  fast_gbk: any
  shared_preferences: any
  fluttertoast: ^8.2.1

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any

  hive_generator: any
  build_runner: any
  
flutter:
  uses-material-design: true

  assets:
    - assets/ugrsical.ics